### ISSUE TITLE
Add option to override package entrypoint

### ISSUE THREAD

**Issue by bmish** [bmish/eslint-doc-generator#209]
In this example, package.json specifies `index.js` is the entry point:

https://github.com/testing-library/eslint-plugin-testing-library/blob/79d8967d3771c08f376ef006ca9235faece5eb1e/package.json#L26

But the package is using semantic-release which specifies the compiled `dist` folder to become the package root in the published package:

https://github.com/testing-library/eslint-plugin-testing-library/blob/79d8967d3771c08f376ef006ca9235faece5eb1e/.releaserc.json#L2

eslint-doc-generator of course doesn't know about semantic-release conventions so it can't load the plugin.

We need an option like `--path-entry dist/index.js` where we could manually specify the entry point to use.

**Comment by ljharb** [comment]
That's a confusing pattern; why wouldn't package.json just always point to dist?

**Comment by bmish** [comment]
Yeah I agree it seems like a confusing pattern. The pattern comes from the [pkgRoot](https://github.com/semantic-release/npm#options) option from semantic-release which you can see in use in the example I linked to above.

**Comment by bmish** [comment]
I was able to workaround this issue in the following PR by adjusting the path to the readme / rule docs / and plugin root:

```
"generate:rules-list": "npm run build && eslint-doc-generator --path-rule-list \"../README.md\" --path-rule-doc \"../docs/rules/{name}.md\" dist/",
```

https://github.com/testing-library/eslint-plugin-testing-library/pull/690/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

So hopefully this option isn't needed anymore.
