### ISSUE TITLE
List rules to be changed when `--check` option is used

### ISSUE THREAD

**Issue by ddzz** [bmish/eslint-doc-generator#377]

**Comment by bmish** [comment]
When using the `--check` option, we currently display these messages, plus a diff of the changes needed in each file.

```
Please run eslint-doc-generator. A rule doc is out-of-date: docs/rules/no-foo.md
```

```
Please run eslint-doc-generator. The rules table in README.md is out-of-date.
```

Are you suggesting something different?

**Comment by ddzz** [comment]
Ah. I missed that. Maybe the README should be updated to mention that a diff will be displayed.
