### ISSUE TITLE
Sort emojis before badges

### ISSUE THREAD

**Issue by RebeccaStevens** [bmish/eslint-doc-generator#401]
It would be nice to have the option to sort the emojis before the badges.

Current:

| 💼                             | Spacer |
| :---------------------------- | :-: |
| 🎨 ![badge-custom-ruleset][] ✅ 🔒 | ====================================================================== |

Ideal:

| 💼                             | Spacer |
| :---------------------------- | :-: |
| 🎨 ✅ 🔒 ![badge-custom-ruleset][] | ====================================================================== |

[badge-custom-ruleset]: https://img.shields.io/badge/-custom--ruleset-blue.svg

**Comment by bmish** [comment]
Good point. That would definitely look better.

I do want to note that the best aesthetic generally comes from using all badges or all emojis, so I usually recommend that.
