### ISSUE TITLE
Poor error message for package.json exports pointing to non-existent path

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bmish/eslint-doc-generator#446]
When the file specified in a `package.json`'s `"main"` entry doesn't exist, `eslint-doc-generator` exits with an only somewhat informative message:

```plaintext
$ npm run update:eslint-docs

> eslint-plugin-expect-type@0.2.2 update:eslint-docs
> eslint-doc-generator

Unable to determine plugin entry point.
```

Is there a way this package could provide a more clear error message? For example:

```plaintext
Plugin entry point `dist/index.js` does not appear to exist on disk.
```

See https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/tree/7c55e1e6cda11eeeb4a7fdefd6e322cb32154d17:

```shell
git clone https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type
cd eslint-plugin-expect-type
git checkout 7c55e1e6cda11eeeb4a7fdefd6e322cb32154d17
npm i
npm run update:eslint-docs
```

The issue is that the package specifies `"main": "./dist/index.js"` and needs to run `npm run build` to generate that before `npm run update:eslint-docs`.

[Example GitHub Actions run](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/actions/runs/4885810867/jobs/8720352650)

**Comment by bmish** [comment]
Good idea to improve this error message. Will try to look into it sometime.
