### ISSUE TITLE
Make the `path-rule-doc` parameter can accept a function

### ISSUE THREAD

**Issue by hyoban** [bmish/eslint-doc-generator#501]
In https://github.com/eslint-react/eslint-react, different categories of eslint rules are organized under different packages. Support for passing a function will greatly improve flexibility, and can help us remove this [patch](https://github.com/eslint-react/eslint-react/blob/main/patches/eslint-doc-generator%401.5.4.patch).

If you agree, I'd be happy to implement this feature.

**Comment by bmish** [comment]
Neat, would be open to a PR for that.

**Comment by bmish** [comment]
Note it would be similar to how we accept a function for the `urlRuleDoc` option.
