### ISSUE TITLE
Add notice link to explain "type information"

### ISSUE THREAD

**Issue by bmish** [bmish/eslint-doc-generator#514]
For these notices/legends:

> 💭 This rule requires type information.

> 💭 Requires type information.

We should probably add a link on "type information" to the @typescript-eslint docs explaining what this is / how to set it up.

* https://typescript-eslint.io/linting/typed-linting/

@JoshuaKGoldberg do you agree?

Related:

* https://github.com/bmish/eslint-doc-generator/pull/509
* https://github.com/bmish/eslint-doc-generator/issues/515

**Comment by JoshuaKGoldberg** [comment]
I agree 🙂 good call!

**Comment by bmish** [comment]
Okay I'll give you first pass at it or otherwise I'll get to it in the coming days.
