### ISSUE TITLE
Peer dependency warnings on ESLint v9

### ISSUE THREAD

**Issue by MikeMcC399** [bmish/eslint-doc-generator#525]
## Issue

Installing [eslint-doc-generator](https://www.npmjs.com/package/eslint-doc-generator) on ESLint `v9` shows peer dependency warnings
> npm WARN ERESOLVE overriding peer dependency

## Desired behavior

Installing the current version of [eslint-doc-generator](https://www.npmjs.com/package/eslint-doc-generator) on ESLint `v9` should show no peer dependency warnings.

## Steps to reproduce

Ubuntu `22.04.4` LTS, Node.js `20.12.2` LTS

```shell
mkdir eslint-doc-gen-test
cd eslint-doc-gen-test
git init
npm init -y
npm install eslint@9 eslint-doc-generator@latest --save-dev
npm ci
```

## Logs

```text
$ npm ci
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @typescript-eslint/utils@5.62.0
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   2 more (@eslint-community/eslint-utils, eslint-doc-generator)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/utils@5.62.0
npm WARN node_modules/eslint-doc-generator/node_modules/@typescript-eslint/utils
npm WARN   @typescript-eslint/utils@"^5.38.1" from eslint-doc-generator@1.7.0
npm WARN   node_modules/eslint-doc-generator
npm WARN
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/utils@5.62.0
npm WARN   node_modules/eslint-doc-generator/node_modules/@typescript-eslint/utils
npm WARN     @typescript-eslint/utils@"^5.38.1" from eslint-doc-generator@1.7.0
npm WARN     node_modules/eslint-doc-generator

added 159 packages, and audited 160 packages in 2s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

## Environment / versions

| Component              | version        |
| ---------------------- | -------------- |
| Ubuntu                 | `22.04.4` LTS  |
| Node.js                | `v20.12.2` LTS |
| ESLint                 | `v9.2.0`       |
| `eslint-doc-generator` | `1.7.0`        |

## Other

- `eslint-doc-generator@1.7.0` depends on `"@typescript-eslint/utils": "^5.38.1"`
- `"@typescript-eslint/utils": "^5.38.1"` resolves to `@typescript-eslint/utils@5.62.0`
- [@typescript-eslint/utils@5.62.0](https://github.com/typescript-eslint/typescript-eslint/blob/v5.62.0/packages/utils/package.json) depends on `"eslint": "^6.0.0 || ^7.0.0 || ^8.0.0"`
- [@typescript-eslint/utils@7.8.0](https://github.com/typescript-eslint/typescript-eslint/blob/v7.8.0/packages/utils/package.json) depends on `"eslint": "^8.56.0"`

See also
- https://github.com/typescript-eslint/typescript-eslint/issues/8211

**Comment by ljharb** [comment]
peer dep warnings mean it’s not yet compatible and you shouldn’t yet be trying to install them together.

see #376 as well.

**Comment by MikeMcC399** [comment]
@ljharb 

> peer dep warnings mean it’s not yet compatible and you shouldn’t yet be trying to install them together.

To make it clearer I will add a new issue requesting support of  ESLint `9.x` by `eslint-doc-generator`.
This issue was just to highlight the problem and provide steps to reproduce.

**Comment by MikeMcC399** [comment]
- Added https://github.com/bmish/eslint-doc-generator/issues/526

**Comment by bmish** [comment]
I'd like to fix this warning, but it will require a lot of dependency updates as well as a major release to drop old Node versions, so it may not be easy/immediate.

It's not great, but you may be able to use `npm ci --force` for now.

**Comment by MikeMcC399** [comment]
## Workaround

Provided you don't have `eslint@9` installed globally, you can install `eslint-doc-generator` globally, avoiding peer dependency warnings, and use it to generate documentation for ESLint `v9` plugins.

```shell
npm install eslint-doc-generator --global
```

**Comment by MikeMcC399** [comment]
- Closing in favor of #526
