### ISSUE TITLE
Migrate to ESLint flat config for CI tests

### ISSUE THREAD

**Issue by MikeMcC399** [bmish/eslint-doc-generator#529]
## What would you like?

Migrate tests running in [.github/workflows/ci.yml](https://github.com/bmish/eslint-doc-generator/blob/main/.github/workflows/ci.yml) to use ESLint flat configuration.

## Why is this needed?

1. The script `lint`, used in [CI](https://github.com/bmish/eslint-doc-generator/blob/main/.github/workflows/ci.yml), relies on running `eslint`.
1. The configuration for ESLint is contained in [.eslintrc.cjs](https://github.com/bmish/eslint-doc-generator/blob/main/.eslintrc.cjs) which is a [standard configuration](https://eslint.org/docs/v8.x/use/configure/configuration-files) for ESLint `v8`.
1. ESLint configuration `.eslintrc` is [deprecated](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated) in ESLint `v9` and is [planned to be removed](https://eslint.org/blog/2023/10/flat-config-rollout-plans/#eslintrc-removed-in-eslint-v10.0.0) in ESLint `v10`.
1. ESLint `v8` [support ceased](https://eslint.org/version-support/) on Oct 5, 2024.
1. ESLint [flat configuration](https://eslint.org/docs/latest/use/configure/configuration-files) is the standard for ESLint `v9` and later.
1. To ensure future support for internal linting of this repo, the deprecated `.eslintrc.cjs` configuration needs to be replaced by a flat configuration.

## Other

| Module                                                                                  | Original | Flat prerequisite | Current                   |
| --------------------------------------------------------------------------------------- | -------- | ----------------- | ------------------------- |
| [eslint](https://github.com/eslint/eslint)                                              | `8.33.0` | `8.57.1`          | `8.57.1`                  |
| [eslint-plugin-square](https://github.com/square/eslint-plugin-square)                  | `24.0.0` | unavailable       | removed                   |
| [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node)                  | `11.1.0` | unmaintained      | `eslint-plugin-n@17.11.1` |
| [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn)          | `45.0.2` | >= `50.0.0`       | `56.0.0`                  |
| [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest)              | `27.2.1` | >= `27.9.0`       | `27.9.0`                  |
| [@typescript-eslint/eslint-plugin](https://typescript-eslint.io/packages/eslint-plugin) | `5.52.0` | >= `7.0.0`        |                           |
| [@typescript-eslint/parser](https://typescript-eslint.io/packages/parser/)              | `5.52.0` | >= `7.0.0`        |                           |
| [@typescript-eslint/utils](https://typescript-eslint.io/packages/utils/)                | `5.52.0` | >= `7.0.0`        |                           |

### Comments

1. [eslint](https://github.com/eslint/eslint) should be updated to the latest `8.*` version to avoid any resolved issues supporting flat configurations in ESLint `v8`. Edit: done with PR #530
2. [eslint-plugin-square](https://github.com/square/eslint-plugin-square) says "It is generally not recommended for public usage outside of Square." and this plugin offers no support for flat configurations. Edit: done with PR #539
3. [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node) states "This project has been no longer maintained. Please consider to use https://github.com/eslint-community/eslint-plugin-n." Edit: done with PR #540

**Comment by MikeMcC399** [comment]
Partial resolution through:

- PR #530 
- PR #531

**Comment by ddzz** [comment]
I would recommend removing `eslint-plugin-square` entirely. Per its README, it's not meant for use in projects outside of Square's organization.

**Comment by MikeMcC399** [comment]
@ddzz 

> I would recommend removing `eslint-plugin-square` entirely. Per its README, it's not meant for use in projects outside of Square's organization.

Thank you for your guidance!

I guess it's no coincidence that [eslint-plugin-square@24.0.0](https://github.com/square/eslint-plugin-square/releases/tag/v24.0.0) currently used in this repo was released by @bmish, who was apparently working at [Square](https://github.com/square) at that time. I assume that this was done for convenience.

There are two issues mentioned in the original post supporting the removal:

- [eslint-plugin-square](https://github.com/square/eslint-plugin-square) says "It is generally not recommended for public usage outside of Square." and this plugin offers no support for flat configurations.

Removing [eslint-plugin-square](https://github.com/square/eslint-plugin-square), whilst preserving the linting functioning it was providing, requires adding back some other ESLint plugins it uses.

**Comment by MikeMcC399** [comment]
@ddzz 

> I would recommend removing `eslint-plugin-square` entirely. Per its README, it's not meant for use in projects outside of Square's organization.

- See PR #539 to implement your suggestion.

**Comment by MikeMcC399** [comment]
- A remaining prerequisite is #545
