### ISSUE TITLE
Add support for Node 20.x and 22.x

### ISSUE THREAD

**Issue by ddzz** [bmish/eslint-doc-generator#543]
First attempt at adding it is failing in CI: https://github.com/bmish/eslint-doc-generator/pull/542

**Comment by MikeMcC399** [comment]
I suggest to add support node Node.js `20.x` and `22.x`, since Node.js 22.x is [planned to become LTS](https://github.com/nodejs/release#release-schedule) on Oct 29, 2024.

Some Jest compatibility issues have to be resolved first though.

**Comment by ddzz** [comment]
> I suggest to add support node Node.js `20.x` and `22.x`, since Node.js 22.x is [planned to become LTS](https://github.com/nodejs/release#release-schedule) on Oct 29, 2024.
> 
> Some Jest compatibility issues have to be resolved first though.

Thanks, I haven't used Node much recently, so I wasn't aware a new LTS version was a week away. Issue has been updated.

**Comment by MikeMcC399** [comment]
@ddzz 

- I've added a separate issue for the Jest incompatibility #546. I would guess that the issue may be solvable by updating some TypeScript and Jest configurations, possibly also needing some dependency updates. I noticed also that [jest.config.cjs](https://github.com/bmish/eslint-doc-generator/blob/main/jest.config.cjs) is using some deprecated calls.
