### ISSUE TITLE
Migrate @typescript-eslint/* linting to 7.*

### ISSUE THREAD

**Issue by MikeMcC399** [bmish/eslint-doc-generator#545]
# What would you like?

Migrate the set of TypeScript ESLinters from the current `v5` version to `v7`. These npm modules are currently configured:

- [@typescript-eslint/eslint-plugin@5.52.0](https://typescript-eslint.io/packages/eslint-plugin)
- [@typescript-eslint/parser@5.62.0](https://typescript-eslint.io/packages/parser/)
- [@typescript-eslint/utils@5.52.0](https://typescript-eslint.io/packages/utils/)

## Why is this needed?

- To achieve the requirements of https://github.com/bmish/eslint-doc-generator/issues/529 a minimum version of [typescript-eslint@7.0.0](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/) is required to support flat config files.

## Other

The [typescript-eslint blog](https://typescript-eslint.io/blog/) contains additional information including migration instructions:

- [Announcing typescript-eslint v6](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6), Jul 9, 2023
- [Announcing typescript-eslint v7](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7), Feb 12, 2024

Also:

- [Announcing typescript-eslint v8](https://typescript-eslint.io/blog/announcing-typescript-eslint-v8), Jul 31, 2024, however the configured version [eslint-plugin-jest@27.9.0](https://github.com/jest-community/eslint-plugin-jest/releases/tag/v27.9.0) currently prevents `v8` usage.

**Comment by MikeMcC399** [comment]
I made an initial test of migrating and found a significant number of errors reported when running `npm run lint`.

Unfortunately I don't expect to be able to tackle this migration since I don't have any TypeScript background to draw on and I believe that it will need TypeScript expertise to successfully complete the migration.

**Comment by bmish** [comment]
@MikeMcC399 @ddzz thanks for your help while I've been traveling. I'm still traveling with limited internet but I'll try to get a bunch of these issues unblocked in the next week or two.

**Comment by bmish** [comment]
I started looking into things but it's a bit of a mess:

* jest snapshot tests failure starting in Node 20 with some of the strings being cut off
* A bunch of interconnected dependencies related to Node, ESLint, TypeScript needing to be updated at the same time and resulting errors that need to be fixed

It's going to take some focus to get everything updated. I'll try again soon.

**Comment by bmish** [comment]
@MikeMcC399 really appreciate all the issues and PRs you filed.

I believe I have addressed everything related to updating the dev environment (Node, ESLint, TypeScript, and all other dependencies) for this repository. Please let me know if I have missed anything.

I do apologize for the delay, as there were a LOT of issues to untangle, and I was traveling and had other commitments the past few months.

This should enable much easier development going forward.

I'd like to release a major release soon to clear the pipeline with the breaking change of dropping all the old Node versions:
* https://github.com/bmish/eslint-doc-generator/pull/575

Are there any other breaking changes you had in mind that we should consider for inclusion with that? We don't necessarily need to include anything else, as nothing else is ready now, and we can perform additional major releases later when other things are ready. Just let me know what you plan to work on next or what you had in mind.
