### ISSUE TITLE
Option to consolidate rule doc notices

### ISSUE THREAD

**Issue by bmish** [bmish/eslint-doc-generator#99]
Example of eslint-plugin-unicorn combining the fixable/suggestions notices into one:

```md
🔧💡 This rule is [auto-fixable](https://eslint.org/docs/user-guide/command-line-interface#fixing-problems) and provides [suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions).
```

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-push-push.md

**Comment by sindresorhus** [comment]
I would make it the default with an opt-out instead. I think this package should provide good defaults.
